### ISSUE TITLE
klávesnice zakryje pole pro psaní

### ISSUE THREAD

**Issue by jsovis** [teamzr/teamzr-client#2]
Při kliknutí do textového pole (**messaging/přidání nového zájmu**) se zobrazí klávesnice a překryje ono textové pole, které tak nelze vidět.

**Comment by brocklj** [comment]
Rozumím, v Expo je tento problém není, objevuje se jen a pouze v produkčním buildu.

**Comment by jsovis** [comment]
A to je právě problém, ne?

**Comment by jsovis** [comment]
Neaktuální issue.
